In this notebook we'll be doing fundamentals of TF.


##Intro To Tensors

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
print(tf.__version__)

2.8.2


In [ ]:
#Creating tensors with tf.constant()
scalar=tf.constant(8)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
#Checke the number of dims of a tensor(ndim means number of dims)
scalar.ndim

0

In [ ]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix=tf.constant([[10,7],
                    [5,6]]) #a tensor of 2 dimensions 
                    
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 5,  6]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
matrix2=tf.constant([[10., 6.],
                     [4.,6.],
                     [5.,8.]],dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  6.],
       [ 4.,  6.],
       [ 5.,  8.]], dtype=float16)>

In [ ]:
matrix2.ndim

2

In [ ]:
#Creating a tensor
tensor=tf.constant([[[1 ,2, 3],
                     [4,5,6]],
                    [[7, 8, 9],
                     [10,11,12]],
                    [[13,654,76],
                     [16,75,45]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[  7,   8,   9],
        [ 10,  11,  12]],

       [[ 13, 654,  76],
        [ 16,  75,  45]]], dtype=int32)>

In [ ]:
tensor.ndim

3

*Scalar:a single number
*Vector:A Number with direction(e.g wind speed and direction)
*Matrix:a 2-Dimensional array of numbers
*Tensor:an n-dimenstional array of numbers(when n can be any number)


In [ ]:
tf.Variable

tensorflow.python.ops.variables.Variable

In [ ]:
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,8])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  8], dtype=int32)>)

In [ ]:
changeable_tensor[0]

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [ ]:
unchangeable_tensor.ndim

1

In [ ]:
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
v=tf.Variable([[1,3,4],
               [4,6,7],
               [5,7,8]])

#v=tf.Variable(1.,shape=tf.TensorShape(None))



In [ ]:
w=tf.constant([[3,6,7],
               [4,7,8]])

In [ ]:
w,v

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[3, 6, 7],
        [4, 7, 8]], dtype=int32)>,
 <tf.Variable 'Variable:0' shape=(3, 3) dtype=int32, numpy=
 array([[1, 3, 4],
        [4, 6, 7],
        [5, 7, 8]], dtype=int32)>)

In [ ]:
tf.matmul(w,v)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 62,  94, 110],
       [ 72, 110, 129]], dtype=int32)>

Random Tensors of some arbitrary size which contain random numbers

In [ ]:
#Creating random tensors


In [ ]:
random1=tf.random.Generator.from_seed(42)
random1=random1.normal(shape=(3,2))
random1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
random2=tf.random.Generator.from_seed(7)
random2=random2.normal(shape=(3,2))
random2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.2878567 ],
       [-0.8757901 , -0.08857017],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [ ]:
random1==random2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

In [ ]:
not_shuffled=tf.constant([[4,5,8],
                          [4,89,6],
                          [2,77,7]])


not_shuffled.ndim

2

In [ ]:
tf.random.set_seed(42)

In [ ]:
tf.random.set_seed(42)
shuffled=tf.random.shuffle(not_shuffled,seed=42)
shuffled


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 4,  5,  8],
       [ 4, 89,  6],
       [ 2, 77,  7]], dtype=int32)>

Read through TF docs on random seed gen
and pract writing 5 random tensors and shuffle them

In [ ]:
t1=tf.constant([[4,5],
                [5,7],
                [7,9]])
t1

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[4, 5],
       [5, 7],
       [7, 9]], dtype=int32)>

In [ ]:
tf.random.shuffle(t1)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[5, 7],
       [7, 9],
       [4, 5]], dtype=int32)>

In [ ]:
tf.random.set_seed(1234)
print(tf.random.uniform([2,2]))
print(tf.random.uniform([2,2]))

tf.Tensor(
[[0.5380393  0.36461866]
 [0.5816301  0.24382842]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[0.3253647  0.1387006 ]
 [0.64804935 0.30401838]], shape=(2, 2), dtype=float32)


In [ ]:
tf.Variable([1,2,3])

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
r1=tf.random.Generator.from_seed(42)

In [ ]:
r1=r1.normal(shape=(2,3))

In [ ]:
r1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
tf.random.shuffle(r1)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193765, -1.8107855 ]], dtype=float32)>

In [ ]:
r2=tf.random.Generator.from_seed(55)
r2=r2.normal(shape=(3,3))
tf.random.shuffle(r2)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.33149615, -0.67958915,  0.44723678],
       [-0.17811586,  0.24882519,  0.49689844],
       [-0.04082382,  2.6791053 ,  1.0914806 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(21)
r3=tf.random.Generator.from_seed(20)
r3=r3.normal(shape=(3,3,3))
tf.random.shuffle(r3)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-1.7166729 ,  0.3738578 , -0.14371012],
        [-0.34646833,  1.1456194 , -0.416     ],
        [ 0.43369916,  1.0241015 , -0.74785167]],

       [[ 2.0261486 , -0.06997604,  0.85445154],
        [ 0.1175475 ,  0.03493892, -1.5700307 ],
        [ 0.44575813,  0.10944034, -0.8035768 ]],

       [[ 0.88051325, -1.6833194 ,  0.86754173],
        [-0.19625713, -1.322665  , -0.02279496],
        [-0.1383193 ,  0.44207528, -0.7531523 ]]], dtype=float32)>

In [ ]:
tf.random.set_seed(420)
r4=tf.random.Generator.from_seed(420)
r4=r4.normal(shape=(3,3,3))
tf.random.shuffle(r4)

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[ 0.7478407 ,  0.833674  , -1.1704516 ],
        [ 0.09289497, -0.5565577 , -1.6673356 ],
        [-0.97270095,  0.02318937, -0.20218365]],

       [[ 0.6356361 , -0.08795371, -1.3398387 ],
        [-0.00641572, -1.1475449 ,  0.6519857 ],
        [-0.5087066 , -0.55476016,  0.9272294 ]],

       [[-0.72668934,  0.5584023 ,  0.9341211 ],
        [-0.1929333 , -0.01480407,  0.8661827 ],
        [-1.6809249 , -1.1837702 ,  1.6152605 ]]], dtype=float32)>

In [ ]:
r5=tf.constant([[10,6],
                [6,8],
                [5,3]])

tf.random.shuffle(r5)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  6],
       [ 5,  3],
       [ 6,  8]], dtype=int32)>

In [ ]:
#If we want our shuffled tensors to be in the same order,we've got to use the global level random seed and operation random seed
tf.random.set_seed(42)
tf.random.shuffle(r5,seed=41)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 6,  8],
       [ 5,  3],
       [10,  6]], dtype=int32)>

In [ ]:
tf.ones([3,3,3])

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,3,3))

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [ ]:
 n1=np.arange(1,25,dtype=np.int32)
 n1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
a=tf.constant(n1,shape=(3,2,4)) #converting our numpy array to a tensor
a

<tf.Tensor: shape=(3, 2, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]],

       [[17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

Shape
Rank
Axis or Dimension
Size

In [ ]:
rank3_t=tf.zeros(shape=(3,3,3))
rank3_t

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]], dtype=float32)>

In [ ]:
rank5_t=tf.zeros(shape=(2,2,2,2,2))
rank5_t

<tf.Tensor: shape=(2, 2, 2, 2, 2), dtype=float32, numpy=
array([[[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]],



       [[[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.]]]]], dtype=float32)>

In [ ]:
rank4_t=tf.zeros(shape=(3,3,3,3))
rank4_t

<tf.Tensor: shape=(3, 3, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank4_t.shape,rank4_t.ndim,tf.size(rank4_t)

(TensorShape([3, 3, 3, 3]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=81>)

In [ ]:
print("Datatype of every element:",rank4_t.dtype)
print("Number of dim or rank:",rank4_t.ndim)
print("Shape of our tensor",rank4_t.shape)
print("Element along the 0 axis:",rank4_t.shape[0])
print("Elements along the last axis",rank4_t.shape[-1])
print("Total number of elements in our tensor:",tf.size(rank4_t).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dim or rank: 4
Shape of our tensor (3, 3, 3, 3)
Element along the 0 axis: 3
Elements along the last axis 3
Total number of elements in our tensor: 81


In [ ]:
list1=[1,2,3,4]
list1[:2]

[1, 2]

In [ ]:
#Get the first 2 elements of each dimension
rank4_t[:2,:2,:2,:2]


<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
#Get the first element from each dimension from each index except for the final one
rank4_t[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 3), dtype=float32, numpy=array([[[[0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank2_t=tf.random.Generator.from_seed(42)
rank2_t=rank2_t.normal(shape=(4,3))
rank2_t

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193765, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535806 ],
       [-0.5716629 ,  0.1480774 , -0.23362991]], dtype=float32)>

In [ ]:
#Get the last item of each row
rank2_t[:,-1]

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.07595026, -1.8107855 , -0.7535806 , -0.23362991], dtype=float32)>

In [ ]:
#Adding in extra dimension to our tensor
rank3_t=rank2_t[...,tf.newaxis]
rank3_t

<tf.Tensor: shape=(4, 3, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702],
        [ 0.07595026]],

       [[-1.2573844 ],
        [-0.23193765],
        [-1.8107855 ]],

       [[ 0.09988727],
        [-0.50998646],
        [-0.7535806 ]],

       [[-0.5716629 ],
        [ 0.1480774 ],
        [-0.23362991]]], dtype=float32)>

The ... is simply a replacement for : : in each line

In [ ]:
rank31_t=rank2_t[:,tf.newaxis,:]
rank31_t

<tf.Tensor: shape=(4, 1, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026]],

       [[-1.2573844 , -0.23193765, -1.8107855 ]],

       [[ 0.09988727, -0.50998646, -0.7535806 ]],

       [[-0.5716629 ,  0.1480774 , -0.23362991]]], dtype=float32)>

In [ ]:
#Alternative to tf.newaxis
tf.expand_dims(rank2_t,axis=-1)#the axis specifies the dimension index

<tf.Tensor: shape=(4, 3, 1), dtype=float32, numpy=
array([[[-0.7565803 ],
        [-0.06854702],
        [ 0.07595026]],

       [[-1.2573844 ],
        [-0.23193765],
        [-1.8107855 ]],

       [[ 0.09988727],
        [-0.50998646],
        [-0.7535806 ]],

       [[-0.5716629 ],
        [ 0.1480774 ],
        [-0.23362991]]], dtype=float32)>

In [ ]:
rank2_t

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193765, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535806 ],
       [-0.5716629 ,  0.1480774 , -0.23362991]], dtype=float32)>

In [ ]:
#get the last element of each column from our rank 2 tensor
rank2_t[-1,:]

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([-0.5716629 ,  0.1480774 , -0.23362991], dtype=float32)>

In [ ]:
#Adding a new axis at the end
rank3_tens=rank2_t[:,:,tf.newaxis]
rank3_tens.shape

TensorShape([4, 3, 1])

In [ ]:
#Adding a new axis in the middle
rank3_tens1=rank2_t[:,tf.newaxis,:]
rank3_tens1.shape

TensorShape([4, 1, 3])

In [ ]:
rank3_tens.shape

TensorShape([4, 3, 1])

In [ ]:
rand2=tf.constant([10,5,6,7,5,4,9,2],shape=(2,2,2))#creating a constant tensor
#of set values,then giving it a diff shape.
rand2

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[10,  5],
        [ 6,  7]],

       [[ 5,  4],
        [ 9,  2]]], dtype=int32)>

In [ ]:
#Creating a random tensor,shuffling it,getting it's attributes,finding
#its elements by indexing,adding a new dimension to it.(initial 3d tensor)

In [ ]:
rand1=tf.random.Generator.from_seed(52) #Generating a random tensor from seed
rand1=rand1.normal(shape=(3,2,3))#Assigning a shape to it
rand1#the tensor and it's 

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[ 1.0034493 ,  0.20857747,  0.35700995],
        [ 1.0648885 ,  1.2432486 , -2.2173238 ]],

       [[ 0.18706243,  0.6617961 ,  0.01380118],
        [-0.24827152,  1.2111493 , -0.7199124 ]],

       [[-0.04082382,  2.6791053 ,  1.0914806 ],
        [ 0.33149615, -0.67958915,  0.44723678]]], dtype=float32)>

In [ ]:
rand1s=tf.random.shuffle(rand1)#Creating a shuffled version of rand1


In [ ]:
rand1s

<tf.Tensor: shape=(3, 2, 3), dtype=float32, numpy=
array([[[ 0.18706243,  0.6617961 ,  0.01380118],
        [-0.24827152,  1.2111493 , -0.7199124 ]],

       [[-0.04082382,  2.6791053 ,  1.0914806 ],
        [ 0.33149615, -0.67958915,  0.44723678]],

       [[ 1.0034493 ,  0.20857747,  0.35700995],
        [ 1.0648885 ,  1.2432486 , -2.2173238 ]]], dtype=float32)>

In [ ]:
#Attributes
print(tf.size(rand1s))#the total number of elements in the tensor
print(rand1s.shape)#the list of dimensions in a tensor
print(rand1s.ndim)#the rank of the tensor
print(rand1s[1])#Getting the 1st element from the first axis
print(rand1s[:,0,:])#Getting the first row from each matrix(in our cube)
print(rand1s[-1,:,:])#Getting all the rows and columns from the last matrix
#from our cube

tf.Tensor(18, shape=(), dtype=int32)
(3, 2, 3)
3
tf.Tensor(
[[-0.04082382  2.6791053   1.0914806 ]
 [ 0.33149615 -0.67958915  0.44723678]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[ 0.18706243  0.6617961   0.01380118]
 [-0.04082382  2.6791053   1.0914806 ]
 [ 1.0034493   0.20857747  0.35700995]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 1.0034493   0.20857747  0.35700995]
 [ 1.0648885   1.2432486  -2.2173238 ]], shape=(2, 3), dtype=float32)


# Manipulating tensors(tensor operations)

In [ ]:
tensor1=tf.constant([[10,5], 
                  [5,8],
                  [3,3]])
tensor1+10

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 15],
       [15, 18],
       [13, 13]], dtype=int32)>

In [ ]:
tf.multiply(tensor1,10
           )

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[100,  50],
       [ 50,  80],
       [ 30,  30]], dtype=int32)>

In [ ]:
#reshaping the matrix
tensor2=tf.reshape(tensor1,shape=(2,3))

In [ ]:
tf.matmul(tensor1,tensor2) 

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[140,  65,  65],
       [114,  49,  49],
       [ 54,  24,  24]], dtype=int32)>

In [ ]:
tensor1t=tf.transpose(tensor1)

In [ ]:
tf.matmul(tensor1,tensor1t)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[125,  90,  45],
       [ 90,  89,  39],
       [ 45,  39,  18]], dtype=int32)>

In [ ]:
tf.tensordot(tensor1,tensor1t,axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[125,  90,  45],
       [ 90,  89,  39],
       [ 45,  39,  18]], dtype=int32)>

In [ ]:
tf.matmul(tensor1,tensor2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[140,  65,  65],
       [114,  49,  49],
       [ 54,  24,  24]], dtype=int32)>

In [ ]:
tf.matmul(tensor1,tensor1t)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[125,  90,  45],
       [ 90,  89,  39],
       [ 45,  39,  18]], dtype=int32)>

In [ ]:
#create a new float tensor
B=tf.constant([[1.5,6.7],[3.6,7.8]])

In [ ]:
B.dtype

tf.float32

In [ ]:
#CHange the float32 to float16 
C=tf.cast(B,dtype=tf.float16)
C.dtype

tf.float16

# Aggreagating Tensors

In [ ]:
random1=tf.random.Generator.from_seed(52)
random1=random1.normal(shape=(4,3,2))
random1

<tf.Tensor: shape=(4, 3, 2), dtype=float32, numpy=
array([[[ 1.0034493 ,  0.20857747],
        [ 0.35700995,  1.0648885 ],
        [ 1.2432486 , -2.2173238 ]],

       [[ 0.18706243,  0.6617961 ],
        [ 0.01380118, -0.24827152],
        [ 1.2111493 , -0.7199124 ]],

       [[-0.04082382,  2.6791053 ],
        [ 1.0914806 ,  0.33149615],
        [-0.67958915,  0.44723678]],

       [[-0.17811586,  0.24882519],
        [ 0.49689844,  0.8259971 ],
        [ 1.0340209 , -0.24918638]]], dtype=float32)>

In [ ]:
tf.reduce_max(random1)

<tf.Tensor: shape=(), dtype=float32, numpy=2.6791053>

In [ ]:
tensor2=tf.random.Generator.from_seed(52)
tensor2=tensor2.normal(shape=(3,3,3))
tensor2

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[ 1.0034493 ,  0.20857747,  0.35700995],
        [ 1.0648885 ,  1.2432486 , -2.2173238 ],
        [ 0.18706243,  0.6617961 ,  0.01380118]],

       [[-0.24827152,  1.2111493 , -0.7199124 ],
        [-0.04082382,  2.6791053 ,  1.0914806 ],
        [ 0.33149615, -0.67958915,  0.44723678]],

       [[-0.17811586,  0.24882519,  0.49689844],
        [ 0.8259971 ,  1.0340209 , -0.24918638],
        [-1.5780283 , -0.92161775,  0.268676  ]]], dtype=float32)>

#Min,Max,Mean,Sum

In [ ]:
numpy1=np.arange(9)
numpy1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
tens1=tf.convert_to_tensor(numpy1)

In [ ]:
tens1=tf.reshape(tens1,shape=(3,3))
tens1

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])>

In [ ]:
tens2=tf.constant([[0.,1.,2.],
                  [3.,4.,5.],
                  [6.,7.,8.],
                   [2.,3.,4.]])

In [ ]:
tf.reduce_mean(tens2,1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([1., 4., 7., 3.], dtype=float32)>

In [ ]:
tf.reduce_min(tens2)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
tf.reduce_prod(tens2)

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
#Operations to Find the mean of a tensor
#0th axis is rows and 1th axis is columns in a 2d tensor
tf.reduce_mean(tens1,)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [ ]:
tf.reduce_mean(tens1,1)#computes the mean of the elements by their axes
#itc the tensor mean about it's 0th axis,i.e about the axis of the rows is 
#computed.

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 4, 7])>

#Exercise to find the variance and standard deviation of our Tensor using
#TensorFlow methods

In [ ]:
a=tf.math.reduce_std(tens2) 

In [ ]:
tf.math.reduce_variance(tens2)

<tf.Tensor: shape=(), dtype=float32, numpy=5.3541665>

In [ ]:
var=a*a
var

<tf.Tensor: shape=(), dtype=float32, numpy=5.3541665>

In [ ]:
tens2

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.],
       [2., 3., 4.]], dtype=float32)>

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(tens2,sample_axis=0)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([4.6875, 4.6875, 4.6875], dtype=float32)>

#Find the positional maximum and minimum

In [ ]:
tensor3=tf.random.Generator.from_seed(42)
tensor3=tensor3.normal(shape=(10,2))
tensor3

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193765, -1.8107855 ],
       [ 0.09988727, -0.50998646],
       [-0.7535806 , -0.5716629 ],
       [ 0.1480774 , -0.23362991],
       [-0.3522796 ,  0.40621266],
       [-1.0523509 ,  1.2054597 ],
       [ 1.6874489 , -0.44629744],
       [-2.3410842 ,  0.99009085]], dtype=float32)>

In [ ]:
tf.argmax(tensor3)#Returns the position of the maximum about the x-axis
#or 0th axis or matrix axis.

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([8, 7])>

In [ ]:
tf.argmax(tensor3,axis=0)

<tf.Tensor: shape=(2,), dtype=int64, numpy=array([8, 7])>

In [ ]:
tf.argmax(tensor3,axis=1)#Return the position of the maximum about the y-axis
#or 1st axis or column-axis

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([1, 0, 0, 0, 1, 0, 1, 1, 0, 1])>

In [ ]:
tensor4=tf.random.Generator.from_seed(42)
tensor4=tensor4.normal(shape=(3,3,3))
tensor4

<tf.Tensor: shape=(3, 3, 3), dtype=float32, numpy=
array([[[-0.7565803 , -0.06854702,  0.07595026],
        [-1.2573844 , -0.23193765, -1.8107855 ],
        [ 0.09988727, -0.50998646, -0.7535806 ]],

       [[-0.5716629 ,  0.1480774 , -0.23362991],
        [-0.3522796 ,  0.40621266, -1.0523509 ],
        [ 1.2054597 ,  1.6874489 , -0.44629744]],

       [[-2.3410842 ,  0.99009085, -0.08763231],
        [-0.635568  , -0.6161736 , -1.9441465 ],
        [-0.48293006, -0.5244748 , -1.0345329 ]]], dtype=float32)>

In [ ]:
tf.reduce_max(tensor4,axis=0)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.5716629 ,  0.99009085,  0.07595026],
       [-0.3522796 ,  0.40621266, -1.0523509 ],
       [ 1.2054597 ,  1.6874489 , -0.44629744]], dtype=float32)>

In [ ]:
tf.reduce_max(tensor4,axis=1)
#in this case 

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.09988727, -0.06854702,  0.07595026],
       [ 1.2054597 ,  1.6874489 , -0.23362991],
       [-0.48293006,  0.99009085, -0.08763231]], dtype=float32)>

In [ ]:
tf.argmax(tensor4,axis=1)
#in this case the 1st axis which is the row axis is fixed, and the max for each position location is computed

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[2, 0, 0],
       [2, 2, 0],
       [2, 0, 0]])>

In [ ]:
tf.reduce_max(tensor4,axis=2)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.07595026, -0.23193765,  0.09988727],
       [ 0.1480774 ,  0.40621266,  1.6874489 ],
       [ 0.99009085, -0.6161736 , -0.48293006]], dtype=float32)>

In [ ]:
tf.argmax(tensor4,axis=0)
#in this case -0.57 at posn (1,1) is the greatest in all 3 matrices defo its
#position being second output is given as 1
#in next case at posn (1,2) is the greatest in all 3 matrices at the position 
#of (1,2) therefore the index of the matrix

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[1, 2, 0],
       [1, 1, 1],
       [1, 1, 1]])>

In [ ]:
tf.argmax(tensor4,axis=1)


<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[2, 0, 0],
       [2, 2, 0],
       [2, 0, 0]])>

In [ ]:
tf.argmax(tensor4,axis=2)

<tf.Tensor: shape=(3, 3), dtype=int64, numpy=
array([[2, 1, 0],
       [1, 1, 1],
       [1, 1, 0]])>

#Squezing a tensor(removing all single dims)


In [ ]:
 tensor5=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))

In [ ]:
tensor5

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
           0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
           0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
           0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
           0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
           0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
           0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
           0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
           0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
           0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ]]]]],
      dtype=float32)>

In [ ]:
tensor5.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
#tensor5.squeeze removes dimensions of size 1 from the shape of a tensor
tensor5_squeezed=tf.squeeze(tensor5)

In [ ]:
tensor5_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.68789124, 0.48447883, 0.9309944 , 0.252187  , 0.73115396,
       0.89256823, 0.94674826, 0.7493341 , 0.34925628, 0.54718256,
       0.26160395, 0.69734323, 0.11962581, 0.53484344, 0.7148968 ,
       0.87501776, 0.33967495, 0.17377627, 0.4418521 , 0.9008261 ,
       0.13803864, 0.12217975, 0.5754491 , 0.9417181 , 0.9186585 ,
       0.59708476, 0.6109482 , 0.82086265, 0.83269787, 0.8915849 ,
       0.01377225, 0.49807465, 0.57503664, 0.6856195 , 0.75972784,
       0.908944  , 0.40900218, 0.8765154 , 0.53890026, 0.42733097,
       0.401173  , 0.66623247, 0.16348064, 0.18220246, 0.97040176,
       0.06139731, 0.53034747, 0.9869994 , 0.4746945 , 0.8646754 ],
      dtype=float32)>

#One Hot Encoding Tensors

In [ ]:
some_list=[0,1,2,3]

tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
#Specifying custom values for one hot encoding
tf.one_hot(some_list,depth=4,on_value="on",off_value="off")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'on', b'off', b'off', b'off'],
       [b'off', b'on', b'off', b'off'],
       [b'off', b'off', b'on', b'off'],
       [b'off', b'off', b'off', b'on']], dtype=object)>

In [ ]:
vect1=[[0,1],
       [2,3]]
tf.one_hot(vect1,depth=4)

<tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[1., 0., 0., 0.],
        [0., 1., 0., 0.]],

       [[0., 0., 1., 0.],
        [0., 0., 0., 1.]]], dtype=float32)>

In [ ]:
cube1=tf.constant([[ [0,1],
                     [2,3] ],
                   [ [4,5],
                     [6,7] ]])

In [ ]:
cube1

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)>

In [ ]:
tf.one_hot(cube1,depth=8)

<tf.Tensor: shape=(2, 2, 2, 8), dtype=float32, numpy=
array([[[[1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0.]],

        [[0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0.]],

        [[0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1.]]]], dtype=float32)>

#More Math Ops

In [ ]:
math1=tf.range(0,9)
math1

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)>

In [ ]:
math1=tf.reshape(math1,shape=(3,3,))
math1

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]], dtype=int32)>

In [ ]:
tf.sqrt(tf.cast(math1,dtype=tf.float32))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.       , 1.       , 1.4142135],
       [1.7320508, 2.       , 2.2360678],
       [2.4494896, 2.6457512, 2.828427 ]], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(math1,dtype=tf.float32))


<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[     -inf, 0.       , 0.6931472],
       [1.0986123, 1.3862944, 1.609438 ],
       [1.7917595, 1.9459102, 2.0794415]], dtype=float32)>

#Check GPU and TPU usage statuses

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sun Aug 21 06:52:34 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   62C    P0    29W /  70W |    286MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

#00TensorFlow Fundamental Exercises

In [ ]:
vector=tf.constant([1])
vector

<tf.Tensor: shape=(1,), dtype=int32, numpy=array([1], dtype=int32)>

In [ ]:
scalar=tf.constant(2)
#scalar
print(scalar.shape)
print(scalar.ndim)
print(tf.size(scalar))

()
0
tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
matrix=tf.constant([0,1,2,434,44,535,5,7,7])
matrix=tf.reshape(matrix,shape=(3,3))
matrix


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[  0,   1,   2],
       [434,  44, 535],
       [  5,   7,   7]], dtype=int32)>

In [ ]:
#Create two tensors containing random values between 0 and 1 with shape [5, 300]
op1=tf.random.uniform(shape=(5,300),minval=0,maxval=1)
op1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.7402308 , 0.33938193, 0.5692506 , ..., 0.08656633, 0.19666708,
        0.7110305 ],
       [0.13257599, 0.81292987, 0.01284087, ..., 0.02695906, 0.2927854 ,
        0.06227863],
       [0.282601  , 0.47868013, 0.77569485, ..., 0.28239357, 0.632112  ,
        0.44452012],
       [0.02029276, 0.7841259 , 0.16919017, ..., 0.26143157, 0.43055534,
        0.47421408],
       [0.2616079 , 0.00913954, 0.20257103, ..., 0.3548187 , 0.9939178 ,
        0.35239196]], dtype=float32)>

In [ ]:
op2=tf.random.uniform(shape=(5,300),minval=0,maxval=1)
op2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.803156  , 0.49777734, 0.37054038, ..., 0.42893624, 0.49179256,
        0.39297235],
       [0.14517438, 0.72666824, 0.80103934, ..., 0.832801  , 0.649397  ,
        0.29312778],
       [0.4216962 , 0.6768439 , 0.5627917 , ..., 0.56929183, 0.90308595,
        0.31530714],
       [0.6198498 , 0.70206463, 0.994668  , ..., 0.03745186, 0.23192072,
        0.23984468],
       [0.01790595, 0.40531397, 0.5369972 , ..., 0.62693167, 0.47887897,
        0.25383985]], dtype=float32)>

In [ ]:
mul1=op1 @ tf.transpose(op2)

In [ ]:
mul1

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[72.3417  , 73.84331 , 71.99731 , 69.78643 , 68.59812 ],
       [76.2998  , 75.77642 , 71.65502 , 72.10436 , 75.2994  ],
       [72.80917 , 75.74102 , 71.199   , 73.04656 , 71.71449 ],
       [74.654816, 76.64434 , 73.32848 , 72.21241 , 73.309074],
       [77.44371 , 78.68229 , 71.98376 , 72.70095 , 72.917274]],
      dtype=float32)>

In [ ]:
mul2=op1 * op2

In [ ]:
mul2

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.5945208 , 0.16893664, 0.21093033, ..., 0.03713144, 0.09671941,
        0.2794153 ],
       [0.01924664, 0.5907303 , 0.01028604, ..., 0.02245153, 0.19013397,
        0.0182556 ],
       [0.11917176, 0.32399172, 0.43655464, ..., 0.16076435, 0.5708515 ,
        0.14016037],
       [0.01257846, 0.55050707, 0.16828805, ..., 0.0097911 , 0.09985471,
        0.11373772],
       [0.00468434, 0.00370438, 0.10878008, ..., 0.22244708, 0.47596633,
        0.08945112]], dtype=float32)>

In [ ]:
op4=tf.random.uniform(shape=(1,224,224,3),minval=0,maxval=1)
tf.squeeze(op4)

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.5749372 , 0.19900596, 0.7038239 ],
        [0.05541027, 0.5884645 , 0.5430788 ],
        [0.9185413 , 0.37144518, 0.84554374],
        ...,
        [0.6570301 , 0.7645861 , 0.48230588],
        [0.41497958, 0.4241538 , 0.5199896 ],
        [0.59315014, 0.23632371, 0.15606153]],

       [[0.34459436, 0.24155474, 0.8630327 ],
        [0.92559505, 0.41881108, 0.9492458 ],
        [0.21597803, 0.15805602, 0.9682605 ],
        ...,
        [0.45298254, 0.6097312 , 0.45232892],
        [0.04503286, 0.48371267, 0.7752477 ],
        [0.644374  , 0.65862846, 0.11632323]],

       [[0.18631506, 0.29340136, 0.3898226 ],
        [0.8457128 , 0.86194694, 0.05938876],
        [0.22856331, 0.74509835, 0.32373703],
        ...,
        [0.03299081, 0.8350847 , 0.77849007],
        [0.5707276 , 0.7097032 , 0.07139933],
        [0.6495327 , 0.17728817, 0.2139225 ]],

       ...,

       [[0.79031277, 0.3867849 , 0.21375918],
        [0.25

In [ ]:
tf.reduce_max(op3)

<tf.Tensor: shape=(), dtype=float32, numpy=0.99999976>

In [ ]:
randx=tf.random.Generator.from_seed(52)
randx=randx.normal(shape=(10,))
randx

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([ 1.0034493 ,  0.20857747,  0.35700995,  1.0648885 ,  1.2432486 ,
       -2.2173238 ,  0.18706243,  0.6617961 ,  0.01380118, -0.24827152],
      dtype=float32)>

In [ ]:
tf.argmax(randx)

<tf.Tensor: shape=(), dtype=int64, numpy=4>

In [ ]:
tf.one_hot(tf.cast(randx,tf.int64),depth=9)

<tf.Tensor: shape=(10, 9), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>